import './globals.css';
import type { Metadata } from 'next';
import Layout from './components/layouts';

const keywordsIndore = [
  'Web Development Company in Indore',
  'Mobile App Development Indore',
  'UI/UX Design Services Indore',
  'E-commerce Website Development Indore',
  'Custom Software Development Indore',
  'Digital Marketing Agency Indore',
  'SEO Services in Indore',
  'PPC Management Services Indore',
  'Content Marketing Indore',
  'Social Media Marketing Indore',
  'Graphic Design Services Indore',
  'Brand Identity Services Indore',
  'Video Production Services Indore',
  'UI/UX Designers in Indore',
  'Mobile App Developers Indore',
  'Web Developers in Indore',
  'E-commerce Website Designers Indore',
  'SEO Experts in Indore',
  'Digital Marketing Experts Indore',
  'Content Writers in Indore',
  'Social Media Managers Indore',
  'Graphic Designers in Indore',
  'Software Development Company Indore',
  'Website Design Services Indore',
  'App Development Services Indore',
  'Local SEO Services Indore',
  'Online Marketing Services Indore',
  'Affordable Web Development Indore',
  'Top SEO Companies in Indore',
  'Professional Web Designers Indore',
  'Best SEO Services Indore',
  'Web Development Packages Indore',
  'Affordable SEO Packages Indore',
  'E-commerce Website Developers Indore',
  'Custom Software Developers Indore',
  'Search Engine Optimization Indore',
  'Content Marketing Strategies Indore',
  'Social Media Advertising Indore',
  'Website Redesign Services Indore',
  'App Development Agency Indore',
  'Mobile App Designers Indore',
  'Web Development Solutions Indore',
  'PPC Advertising Agency Indore',
  'Digital Marketing Strategies Indore',
  'Local SEO Experts Indore',
  'E-commerce Development Indore',
  'Custom Software Solutions Indore',
  'UI/UX Design Agency Indore',
  'Content Marketing Agency Indore',
  'Social Media Management Indore',
  'Graphic Design Agency Indore',
  'Website Development Agency Indore',
  'App Development Company Indore',
  'Mobile App Development Agency Indore',
  'Web Design and Development Indore',
  'SEO Optimization Services Indore',
  'PPC Campaign Management Indore',
  'Digital Marketing Company Indore',
  'Local SEO Agency Indore',
  'E-commerce Web Design Indore',
  'Custom Software Development Solutions Indore',
  'UI/UX Design Studio Indore',
  'Content Marketing Services Indore',
  'Social Media Marketing Agency Indore',
  'Graphic Design Studio Indore',
  'Website Design Company Indore',
  'App Development Studio Indore',
  'Mobile App Design Agency Indore',
  'Web Development Firm Indore',
  'SEO Consultancy Services Indore',
  'PPC Services Company Indore',
  'Digital Marketing Agency in Indore',
  'Local SEO Company Indore',
  'E-commerce Website Design Agency Indore',
  'Custom Software Development Company Indore',
  'UI/UX Design Firm Indore',
  'Content Marketing Company Indore',
  'Social Media Advertising Agency Indore',
  'Graphic Design Firm Indore',
  'Website Redesign Agency Indore',
  'App Development Firm Indore',
  'Mobile App Design Studio Indore',
  'Web Development Studio Indore',
  'SEO Services Provider Indore',
  'PPC Advertising Company Indore',
  'Digital Marketing Firm Indore',
  'Local SEO Services Provider Indore',
  'E-commerce Web Development Indore',
  'Custom Software Development Firm Indore',
  'UI/UX Design Services Provider Indore',
  'Content Marketing Firm Indore',
  'Social Media Management Agency Indore',
  'Graphic Design Services Provider Indore',
  'Website Development Services Provider Indore',
  'App Development Services Provider Indore',
  'Mobile App Development Services Provider Indore',
  'Web Design and Development Firm Indore',
  'SEO Optimization Services Provider Indore',
  'PPC Campaign Management Firm Indore',
  'Digital Marketing Services Provider Indore',
  'E-commerce Web Design Firm Indore',
  'Custom Software Development Services Provider Indore',
  'Content Marketing Services Provider Indore',
  'Social Media Marketing Services Provider Indore',
  'Website Redesign Services Provider Indore',
  'Mobile App Design Services Provider Indore',
  'Web Development Solutions Provider Indore',
  'Digital Marketing Strategies Provider Indore',
  'E-commerce Development Provider Indore',
  'Custom Software Solutions Provider Indore',
  'Social Media Management Provider Indore',
  'Web Design and Development Provider Indore',
  'PPC Campaign Management Provider Indore',
  'E-commerce Web Design Provider Indore',
  'Custom Software Development Solutions Provider Indore',
  'SEO Optimization Services Provider Indore',
];

export const metadata: Metadata = {
  title: {
    default: 'dunolabs | creative software agency',
    template: '%s | dunolabs ',
  },
  description:
    'Your go-to software agency for creative design, development, and effective web app marketing. We craft web apps, products, and tools to elevate your online presence.',
  keywords: keywordsIndore,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <script async src="https://cdn.splitbee.io/sb.js"></script>
      </head>
      <body className={'app-container'}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
